name: CI

on:
  pull_request:
    branches: [main]

jobs:
  up-build:
    runs-on: ubuntu-latest

    steps:
      - name: Install UP CLI
        run: |
          curl -sL "https://cli.upbound.io" | sh
          sudo mv up /usr/local/bin

      - name: Render MRs
        run: up xpkg build --ignore=".github/**/*.yaml" 
